#!/usr/bin/env python3
"""
Plot generator for Covid data from Johns Hopkins 
"""

import support.args
import importlib
import sys

args = support.args.Args()

try:
    module = importlib.import_module('plotters.' + args.action)
except:
    print("\nNeed to implement plotters." + args.action + "\n")
    sys.exit(1)

module.plot(args)

